

#数据库
spring:
    datasource:
        url: jdbc:mysql://47.52.227.26:3306/sso_test?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        username: hjs
        password: hjs


#mybatis配置
mybatis:
    typeAliasesPackage: com.hjs.starter.model
    mapperLocations: classpath:com/hjs/starter/mapper/*.xml
    configLocation: classpath:mybatis/mybatis-config.xml


